spring:
 cloud:
   gateway:
     routes:
       - id: immo-service
         uri: lb://BUSINESS-SERVICE
         predicates:
           - Path=/api/v1/business/**
         filters:
           - AuthenticationFilter

       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/api/v1/auth/**
           
     globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:5501"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - DELETE
            
 application:
   name: PROP-MGT-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
server:
  port : 8088