spring:
 cloud:
   gateway:
     routes:
       - id: immo-service
         uri: lb://BUSINESS-SERVICE
         predicates:
           - Path=/api/v1/business/**
         filters:
           - AuthenticationFilter

       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/api/v1/auth/**

 application:
   name: PROP-MGT-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
server:
  port : 8088